[package]
name = "sample_contracts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[env]
RUST_TEST_THREADS = "1"

[dependencies]
oxyde_sdk = {path="../oxyde_sdk"}
bincode = "1.3.3"
